### ISSUE TITLE
URGENT - Pin protected wallet not sending funds.

### ISSUE THREAD

**Issue by Bitplicity** [swaponline/MultiCurrencyWallet#3108]
No matter what I try I can not send Bitcoin from a pin protected wallet. The pin is correct and alternatively, when I attempt to enter my 12 word key to send the transaction I get this same error. See screenshot:

![Screenshot_20200727-141417_Chrome](https://user-images.githubusercontent.com/66849208/88577077-6cb5d280-d014-11ea-995f-c64e78d2eab0.jpg)

I have tried lowering the amount to send. Nothing works. Also, please change the error text as I don't want users to see the "server offline" comment. 

Thanks.

**Comment by Bitplicity** [comment]
Problem is present on all devices. Android, IOS and PC.

**Comment by iower** [comment]
Related: #3098

**Comment by shendel** [comment]
@Bitplicity 
need: wallet address, destination address and tested amount
send info to me in telegram @eneeseene

**Comment by noxonsu** [comment]
@Bitplicity did you try to send less amount?

**Comment by noxonsu** [comment]
sending from 3EzXmVCX5CyWHJATCtJ7fu7DWE5KtsdhVo (Balance: 0.00064297 BTC) trying to send ~5$. current mining fee is 200+ sat (extremely high). 

Kim W, [29.07.20 14:46]
Please remove the text the part of the text that says "if the authentication server is offline."

Kim W, [29.07.20 14:46]
Ok

Kim W, [29.07.20 14:47]
And instead of unknown error...please put "insufficient funds you need to reduce the amount to cover the fees."

**Comment by shendel** [comment]
Min Service fee is 0.00078
