### ISSUE TITLE
Dont show info about disabled networks

### ISSUE THREAD

**Issue by shendel** [swaponline/MultiCurrencyWallet#5047]
If I only want to use bsc, these texts do harm instead of help
![image](https://user-images.githubusercontent.com/1880211/158680855-578d25da-1109-4a4f-a736-eb95c415cf09.png)
![image](https://user-images.githubusercontent.com/1880211/158680890-121c7a3c-4325-466a-8c7e-d1c7e8f508cf.png)

**Comment by VitaliyShulik** [comment]
Our client disabled all networks instead of BNB but still when he is on exchange part as first option (default) is still Ethereum instead of Binance.
![telegram-cloud-photo-size-4-5883997400887048937-y](https://user-images.githubusercontent.com/36531102/159106529-77814bfb-fa80-43c0-b676-16f7b2fc21c1.jpg)

both MATIC & ETH shouldn't be there
![telegram-cloud-photo-size-4-5883997400887048939-y](https://user-images.githubusercontent.com/36531102/159106532-fe27029b-8c80-489e-a0ae-fb888d7779f6.jpg)

**Comment by shendel** [comment]
> 

May be need update (Eth disabled)

![image](https://user-images.githubusercontent.com/1880211/160877132-10b16130-bc06-47f6-8b31-ecc2edd92e9f.png)
![image](https://user-images.githubusercontent.com/1880211/160877269-825f03c3-70f3-4d69-affd-258714dc2f7f.png)
