### ISSUE TITLE
Wallet connect is not working on mobile device can please have a way of turning off and just standalone

### ISSUE THREAD

**Issue by Phinetwork** [swaponline/MultiCurrencyWallet#5210]
Wallet connect is not working on mobile device have to turn screenside ways and still doesn't work please can also add option to completely turn off wallet connect if want to just use standalone wallet 

## Steps to reproduce

- steps
- to
- reproduce

## Environment

- Domain: 
- Mainnet or Testnet: 
- Browser: 
- OS: 

## Your version

- [ ] latest
- [ ] not latest (please try to upgrade first)
- [ ] not sure

## Does this affect atomic swap flow?

- [ ] yes
- [ ] no

## Are real funds at risk?

- [ ] yes
- [ ] no

**Comment by Phinetwork** [comment]
Hello wallet connect doesn't work and having lots of reports from users need this fixed and would prefer wallet connect is removed as there's no purpose for it.

**Comment by Phinetwork** [comment]
@shendel we need this fixed lots of users reporting errors wallet connect is not working need it fixed or removed

**Comment by NotEternal** [comment]
@Phinetwork hi. Please, tell use more information. What mobile OS was used (Android, iOS)? What crypto wallet? If possible, send screens with issues (sometimes you're able to see problems directly from the wallet/app UI).
Because it works on our side. There's an external issue with iOS-Metamask setup, so you can't use it at this moment.

**Comment by NotEternal** [comment]
Active issue to discuss and follow the progress: #5212
